### ISSUE TITLE
I am unable to load my style from custom made style file already stored in config folder

### ISSUE THREAD

**Issue by gulzarumair** [karthikn2789/Custom-Matplotlib-Style#2]
fileNotFoundError                         Traceback (most recent call last)
~\anaconda3\lib\site-packages\matplotlib\style\core.py in use(style)
    113             try:
--> 114                 rc = rc_params_from_file(style, use_default_template=False)
    115                 _apply_style(rc)

~\anaconda3\lib\site-packages\matplotlib\__init__.py in rc_params_from_file(fname, fail_on_error, use_default_template)
    983     """
--> 984     config_from_file = _rc_params_in_file(fname, fail_on_error)
    985 

~\anaconda3\lib\site-packages\matplotlib\__init__.py in _rc_params_in_file(fname, fail_on_error)
    913     rc_temp = {}
--> 914     with _open_file_or_url(fname) as fd:
    915         try:

~\anaconda3\lib\contextlib.py in __enter__(self)
    112         try:
--> 113             return next(self.gen)
    114         except StopIteration:

~\anaconda3\lib\site-packages\matplotlib\__init__.py in _open_file_or_url(fname)
    899             encoding = "utf-8"
--> 900         with open(fname, encoding=encoding) as f:
    901             yield f

FileNotFoundError: [Errno 2] No such file or directory: 'scientific'

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-23-4171c0323385> in <module>
      1 import matplotlib.pyplot as plt
      2 # Use our custom style
----> 3 plt.style.use('scientific')
      4 # Create figure
      5 fig = plt.figure()

~\anaconda3\lib\site-packages\matplotlib\style\core.py in use(style)
    115                 _apply_style(rc)
    116             except IOError:
--> 117                 raise IOError(
    118                     "{!r} not found in the style library and input is not a "
    119                     "valid URL or path; see `style.available` for list of "

OSError: 'scientific' not found in the style library and input is not a valid URL or path; see `style.available` for list of available styles

**Comment by karthikn2789** [comment]
Thank you for raising the issue.

I have tried copying my custom mplstyle file to matplotlib config folder and it works without an issue. Following are the steps that I did.
1. Checked the location of matplotlib config folder using the command 
```
import matplotlib
print(matplotlib.get_configdir())
```
2. It will be under `/home/<user>/.config/matplotlib`. According to matplotlib.org, we may have to create a folder named `stylelib` in the config directory, if it does not exist already. So, I created the folder and copied my `demo.mplstyle`. NOTE: This is the same file as `demo_style.mplstyle`. I had renamed it to check if the new file gets detected while using `plt.style.available`.
3. After copying `demo.mplstyle` to `/home/<user>/.config/matplotlib/stylelib/`, restarted the kernel of the Jupyter Notebook and executed the following lines of code.
```
import matplotlib.pyplot as plt
plt.style.available # Showed 'demo' in the list
plt.style.use('demo') # Showed no error and the style got applied to subsequent graphs
```

I kindly ask you to try these steps. If you still do not get your desired outcome, I request you to share the path of the scientific.mplstyle file along with the steps you did, so I can reproduce the error.

Thank you.
